apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: main-pool
  namespace: metallb-system
spec:
  # Professional dummy range based on documentation standards
  addresses:
  - 198.51.100.101-198.51.100.140
  autoAssign: true
